theme = "custom" # tema customizado

[editor]
mouse = true                                                # Scroll and select with the mouse
line-number = 'relative'
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
idle-timeout = 200
color-modes = true                                          # colorear los modos de diferentes colores

[editor.statusline]
left = ["mode", "separator", "file-name", "file-modification-indicator"]
center = ["spinner", "diagnostics"]
right = [
  "version-control",
  "spacer",
  "separator",
  "spacer",
  "position-percentage",
  "position",
]
separator = '|'
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.indent-guides]
render = true   # habilitar el la marca de indentado
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 5

# NOTE: -----------------[Normal Mode]---------------------
[keys.normal]
# Desabilitar las teclas de movimiento en modo normal
"left" = "no_op"
"right" = "no_op"
"up" = "scroll_up"
"down" = "scroll_down"

# ir al inicio y final de la linea
0 = "goto_line_start"
"$" = "goto_line_end"

D = "kill_to_line_end"
d = { d = ["extend_line_below", "delete_selection"] }

[keys.normal.space]
w = [":write", ":format"]
q = ":quit"

# buffer next, prev, close
k = ":buffer-next"
j = ":buffer-previous"
x = ":buffer-close"

"/" = "toggle_comments"

# NOTE: -----------------[Insert Mode]---------------------
[keys.insert]
k = { j = 'normal_mode' } # escapar al modo "normal"
K = { J = 'normal_mode' } # escapar al modo "normal"

# desabilitar las teclas de movimiento en modo insertar
"left" = "no_op"
"right" = "no_op"
"up" = "scroll_up"
"down" = "scroll_down"

# moverse en modo insertar
"C-h" = "move_char_left"
"C-l" = "move_char_right"
"C-j" = "move_line_down"
"C-k" = "move_line_up"


# TODO: Sección de 'keys.select'
[keys.select]
# ir al inicio y final de la linea
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.select.space]
"/" = "toggle_comments"
