theme = "custom" # tema customizado

[editor]
line-number = 'relative'
mouse = false
middle-click-paste = true
cursorline = true
color-modes = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "position"]
separator = '|'
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true   # habilitar el la marca de indentado
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 5

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

# TODO: Sección de 'keys.normal'
[keys.normal]
# Desabilitar las teclas de movimiento en modo normal
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"

# ir al inicio y final de la linea
0 = "goto_line_start"
"$" = "goto_line_end"

D = "kill_to_line_end"
d = { d = ["extend_line_below", "delete_selection"] }


[keys.normal.space]
w = [":write", ":format"]
q = ":quit"

# buffer next, prev, close
k = ":buffer-next"
j = ":buffer-previous"
x = ":buffer-close"

"/" = "toggle_comments"

# TODO: Sección de 'keys.insert'
[keys.insert]
k = { j = 'normal_mode' } # escapar al modo "normal"

# desabilitar las teclas de movimiento en modo insertar
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"

# moverse en modo insertar
"C-h" = "move_char_left"
"C-l" = "move_char_right"
"C-j" = "move_line_down"
"C-k" = "move_line_up"

# TODO: Sección de 'keys.select'
[keys.select]
# ir al inicio y final de la linea
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.select.space]
"/" = "toggle_comments"
