# NOTE: Language Markdown -------------------------------------------
[[language]]
name = "markdown"

[language.auto-pairs]
"*" = "*"
"_" = "_"

# NOTE: Language Lua ------------------------------------------------
[[language]]
name = "lua"
indent = { tab-width = 3, unit = "   " }

# NOTE: Language HTML -----------------------------------------------
[language-server.emmet-lsp]
command = "emmet-language-server"
# args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]
